{% set name = "apache-airflow-providers-cloudant" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 66e3af44da239ed2abb94fa67adf5b8019773e3055e78bd1e7e746c9b520324c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.10,<4.dev0
    - apache-airflow >=2.8.0
    - ibmcloudant 0.9.1

test:
  imports:
    - airflow.providers.cloudant
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-cloudant for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/cloudant/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-cloudant/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
